version: "3"

services:
  mongodb:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-mongodb
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-app
    env_file: ./.env
    environment:
      - DB_HOST=$MONGODB_DB_HOST
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_NAME=$MONGODB_DB_NAME
      - NODE_PORT=$NODE_LOCAL_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT